/**
 * Representative sample dataset used as the offline fallback when the
 * carsome.my scraper can't reach the network. Field names mirror what
 * the live scraper produces so the engine sees the same shape either
 * way.
 *
 * Listings are intentionally heterogeneous (some missing fields, some
 * unusual fields) to exercise schema discovery.
 */

import type { RawListing } from '../engine/types.ts'

export const SAMPLE_LISTINGS: RawListing[] = [
	{
		id: 'csm-101',
		brand: 'Honda',
		model: 'City',
		variant: '1.5 V',
		year: 2019,
		mileage_km: 58200,
		price_myr: 58800,
		owners: 1,
		transmission: 'Automatic',
		fuel: 'Petrol',
		body: 'Sedan',
		colour: 'White',
		location: 'Selangor',
		condition: 'Used',
		seats: 5,
		engine_cc: 1497,
		features_count: 14,
		url: 'https://www.carsome.my/buy-car/honda/city/csm-101',
		image: 'https://img.carsome.my/csm-101.jpg',
	},
	{
		id: 'csm-102',
		brand: 'Toyota',
		model: 'Vios',
		variant: '1.5 G',
		year: 2020,
		mileage_km: 45100,
		price_myr: 67900,
		owners: 1,
		transmission: 'Automatic',
		fuel: 'Petrol',
		body: 'Sedan',
		colour: 'Silver',
		location: 'Kuala Lumpur',
		condition: 'Used',
		seats: 5,
		engine_cc: 1496,
		features_count: 16,
		url: 'https://www.carsome.my/buy-car/toyota/vios/csm-102',
	},
	{
		id: 'csm-103',
		brand: 'Perodua',
		model: 'Myvi',
		variant: '1.5 AV',
		year: 2021,
		mileage_km: 28900,
		price_myr: 49800,
		owners: 1,
		transmission: 'Automatic',
		fuel: 'Petrol',
		body: 'Hatchback',
		colour: 'Red',
		location: 'Penang',
		condition: 'Used',
		seats: 5,
		engine_cc: 1496,
		features_count: 12,
		url: 'https://www.carsome.my/buy-car/perodua/myvi/csm-103',
	},
	{
		id: 'csm-104',
		brand: 'Mazda',
		model: 'CX-5',
		variant: '2.0 GLS',
		year: 2018,
		mileage_km: 82400,
		price_myr: 89000,
		owners: 2,
		transmission: 'Automatic',
		fuel: 'Petrol',
		body: 'SUV',
		colour: 'Black',
		location: 'Johor',
		condition: 'Used',
		seats: 5,
		engine_cc: 1998,
		features_count: 18,
		url: 'https://www.carsome.my/buy-car/mazda/cx-5/csm-104',
	},
	{
		id: 'csm-105',
		brand: 'Honda',
		model: 'Civic',
		variant: '1.5 TC-P',
		year: 2017,
		mileage_km: 95000,
		price_myr: 78000,
		owners: 2,
		transmission: 'Automatic',
		fuel: 'Petrol',
		body: 'Sedan',
		colour: 'Grey',
		location: 'Selangor',
		condition: 'Used',
		seats: 5,
		engine_cc: 1498,
		features_count: 17,
		url: 'https://www.carsome.my/buy-car/honda/civic/csm-105',
	},
	{
		id: 'csm-106',
		brand: 'Proton',
		model: 'X50',
		variant: '1.5T Flagship',
		year: 2022,
		mileage_km: 22000,
		price_myr: 96800,
		owners: 1,
		transmission: 'Automatic',
		fuel: 'Petrol',
		body: 'SUV',
		colour: 'Blue',
		location: 'Kuala Lumpur',
		condition: 'Used',
		seats: 5,
		engine_cc: 1477,
		features_count: 20,
		url: 'https://www.carsome.my/buy-car/proton/x50/csm-106',
	},
	{
		id: 'csm-107',
		brand: 'Toyota',
		model: 'Hilux',
		variant: '2.4 Rogue',
		year: 2021,
		mileage_km: 39400,
		price_myr: 138900,
		owners: 1,
		transmission: 'Automatic',
		fuel: 'Diesel',
		body: 'Pickup',
		colour: 'White',
		location: 'Sabah',
		condition: 'Used',
		seats: 5,
		engine_cc: 2393,
		features_count: 19,
		url: 'https://www.carsome.my/buy-car/toyota/hilux/csm-107',
	},
	{
		id: 'csm-108',
		brand: 'Nissan',
		model: 'Almera',
		variant: '1.0 VLT',
		year: 2020,
		mileage_km: 51200,
		price_myr: 64900,
		owners: 1,
		transmission: 'Automatic',
		fuel: 'Petrol',
		body: 'Sedan',
		colour: 'Silver',
		location: 'Selangor',
		condition: 'Used',
		seats: 5,
		engine_cc: 999,
		features_count: 15,
		url: 'https://www.carsome.my/buy-car/nissan/almera/csm-108',
	},
	{
		id: 'csm-109',
		brand: 'Honda',
		model: 'HR-V',
		variant: '1.8 V',
		year: 2019,
		mileage_km: 67500,
		price_myr: 82900,
		owners: 1,
		transmission: 'Automatic',
		fuel: 'Petrol',
		body: 'SUV',
		colour: 'Pearl White',
		location: 'Penang',
		condition: 'Used',
		seats: 5,
		engine_cc: 1799,
		features_count: 16,
		url: 'https://www.carsome.my/buy-car/honda/hr-v/csm-109',
	},
	{
		id: 'csm-110',
		brand: 'Perodua',
		model: 'Bezza',
		variant: '1.3 Advance',
		year: 2022,
		mileage_km: 18900,
		price_myr: 47500,
		owners: 1,
		transmission: 'Automatic',
		fuel: 'Petrol',
		body: 'Sedan',
		colour: 'Granite Grey',
		location: 'Kuala Lumpur',
		condition: 'Used',
		seats: 5,
		engine_cc: 1329,
		features_count: 13,
		url: 'https://www.carsome.my/buy-car/perodua/bezza/csm-110',
	},
	{
		id: 'csm-111',
		brand: 'BMW',
		model: '320i',
		variant: 'Sport',
		year: 2016,
		mileage_km: 110800,
		price_myr: 89800,
		owners: 3,
		transmission: 'Automatic',
		fuel: 'Petrol',
		body: 'Sedan',
		colour: 'Black',
		location: 'Selangor',
		condition: 'Used',
		seats: 5,
		engine_cc: 1998,
		features_count: 22,
		url: 'https://www.carsome.my/buy-car/bmw/320i/csm-111',
	},
	{
		id: 'csm-112',
		brand: 'Mercedes-Benz',
		model: 'C200',
		variant: 'AMG Line',
		year: 2018,
		mileage_km: 78900,
		price_myr: 168800,
		owners: 1,
		transmission: 'Automatic',
		fuel: 'Petrol',
		body: 'Sedan',
		colour: 'White',
		location: 'Kuala Lumpur',
		condition: 'Used',
		seats: 5,
		engine_cc: 1991,
		features_count: 24,
		url: 'https://www.carsome.my/buy-car/mercedes-benz/c200/csm-112',
	},
	{
		id: 'csm-113',
		brand: 'Toyota',
		model: 'Yaris',
		variant: '1.5 G',
		year: 2020,
		mileage_km: 41000,
		price_myr: 66800,
		owners: 1,
		transmission: 'Automatic',
		fuel: 'Petrol',
		body: 'Hatchback',
		colour: 'Blue',
		location: 'Johor',
		condition: 'Used',
		seats: 5,
		engine_cc: 1496,
		features_count: 15,
		// missing url to exercise auxiliary handling
	},
	{
		id: 'csm-114',
		brand: 'Mitsubishi',
		model: 'Triton',
		variant: '2.4 Adventure X',
		year: 2019,
		mileage_km: 92000,
		price_myr: 88800,
		owners: 2,
		transmission: 'Automatic',
		fuel: 'Diesel',
		body: 'Pickup',
		colour: 'Grey',
		location: 'Sarawak',
		condition: 'Used',
		seats: 5,
		engine_cc: 2442,
		features_count: 17,
		url: 'https://www.carsome.my/buy-car/mitsubishi/triton/csm-114',
	},
	{
		id: 'csm-115',
		brand: 'Honda',
		model: 'Jazz',
		variant: '1.5 V',
		year: 2018,
		mileage_km: 71200,
		price_myr: 56900,
		owners: 2,
		transmission: 'Automatic',
		fuel: 'Petrol',
		body: 'Hatchback',
		colour: 'Red',
		location: 'Selangor',
		condition: 'Used',
		seats: 5,
		engine_cc: 1497,
		features_count: 14,
		url: 'https://www.carsome.my/buy-car/honda/jazz/csm-115',
	},
	{
		id: 'csm-new-1',
		brand: 'Toyota',
		model: 'Corolla Cross',
		variant: '1.8',
		year: 2024,
		mileage_km: 12,
		price_myr: 134000,
		owners: 0,
		transmission: 'Automatic',
		fuel: 'Petrol',
		condition: 'Brand New',
		seats: 5,
		engine_cc: 1798,
	},
	{
		id: 'csm-dup-101',
		brand: 'Honda',
		model: 'City',
		variant: '1.5 V',
		year: 2019,
		mileage_km: 58200,
		price_myr: 58800,
		transmission: 'Automatic',
		fuel: 'Petrol',
		body: 'Sedan',
		condition: 'Used',
	},
	{
		id: 'csm-outlier-1',
		brand: 'Ferrari',
		model: '488',
		year: 2017,
		mileage_km: 8000,
		price_myr: 1450000,
		owners: 1,
		transmission: 'Automatic',
		fuel: 'Petrol',
		body: 'Coupe',
		condition: 'Used',
	},
]
